import = [
	"~/.config/alacritty/fonts.toml",
	"~/.config/alacritty/colors_catppuccin-mocha",
	"~/.config/alacritty/keymaps.toml"
]
live_config_reload = true

[env]
term = "xterm-256color"

[window]
startup_mode = "Windowed"
decorations = "buttonless"
option_as_alt = "OnlyLeft"
dynamic_padding = false
dynamic_title = true
opacity = 0.8
blur = true

[window.dimensions]
columns = 177
lines = 45

[window.padding]
x = 14
y = 12
