[general]
import = [
	"~/.config/alacritty/fonts.toml",
	"~/.config/alacritty/colors_catppuccin-mocha",
	"~/.config/alacritty/keymaps.toml"
]
live_config_reload = true

[env]
term = "xterm-256color"

[window]
startup_mode = "Windowed"
decorations = "Buttonless"
dimensions = { columns = 188, lines = 47 }
padding = { x = 8, y = 8 }
option_as_alt = "OnlyLeft"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
blur = true

