[font]
builtin_box_drawing = true
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Thin"

[font.offset]
x = 0
y = 1
